version: '2'

services:
  <%= project.namespace %>:
    image: <%= project.name %>
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RELEASE
