FROM node:6-slim
MAINTAINER <%= project.namespace %>

#CONTENT TBD
# Probably a custom preconfigured webserver image with shared volume
# to push ./dist content

RUN apt-get update && apt-get install -y git

EXPOSE 8080

COPY package.json /app/

WORKDIR /app
RUN npm install
RUN npm install express morgan

ENV VULCAIN_SERVICE_NAME=<%= project.fullName %>
ENV VULCAIN_SERVICE_VERSION=1.0

COPY src /app/src
COPY ./* /app/

RUN npm run package:prod

ENTRYPOINT ["node", "index.js"]
